/*
 * File: app/view/FieldNach.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.view.FieldNach', {
    extend: 'Ext.form.field.Number',
    alias: 'widget.fieldnach',

    requires: [
        'Osbb.view.FieldNachViewModel'
    ],

    viewModel: {
        type: 'fieldnach'
    },
    width: 133,
    fieldLabel: 'label',
    labelWidth: 55,
    value: 0,
    fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
    hideTrigger: true,
    autoStripChars: true

});