/*
 * File: app/model/MdEnergyTarif.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.model.MdEnergyTarif', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.proxy.Memory'
    ],

    fields: [
        {
            type: 'string',
            name: 'usluga'
        },
        {
            type: 'string',
            name: 'tarif'
        }
    ],

    proxy: {
        type: 'memory',
        data: [
            {
                usluga: 'Тариф по электроэнергии',
                tarif: 'energy'
            },
            {
                usluga: 'Перерасчет по электроэнергии',
                tarif: 'ch_energy'
            },
            {
                usluga: 'Кол-во кВт по домовому эл.сч-ку',
                tarif: 'kwh_nach'
            },
            {
                usluga: 'На основного льготника',
                tarif: 'kwh_osn_lg'
            },
            {
                usluga: 'На каждого следующего льготника',
                tarif: 'kwh_dop_lg'
            },
            {
                usluga: 'Лимит кВт на всех льготников',
                tarif: 'kwh_end_lg'
            }
        ]
    }
});