/*
 * File: app/model/MdUtszn.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.model.MdUtszn', {
    extend: 'Ext.data.Model',
    alias: 'model.mdUtszn',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    idProperty: 'rec_id',

    fields: [
        {
            type: 'int',
            name: 'rec_id'
        },
        {
            type: 'int',
            name: 'house_id'
        },
        {
            type: 'int',
            name: 'lgota_id'
        },
        {
            type: 'int',
            name: 'gr'
        },
        {
            type: 'float',
            name: 'budjet'
        },
        {
            type: 'int',
            name: 'percent'
        },
        {
            type: 'string',
            name: 'house'
        },
        {
            type: 'string',
            name: 'osmd'
        },
        {
            type: 'string',
            name: 'edrpou'
        },
        {
            type: 'string',
            name: 'lgota'
        },
        {
            type: 'string',
            name: 'lgota_ua'
        },
        {
            type: 'float',
            name: 'st'
        },
        {
            type: 'float',
            name: 'nachisleno'
        },
        {
            type: 'float',
            name: 'subsidia'
        },
        {
            type: 'float',
            name: 'oplata'
        },
        {
            type: 'float',
            name: 'doplata'
        },
        {
            type: 'float',
            name: 'fin'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'date',
            name: 'date_akt'
        },
        {
            type: 'string',
            name: 'info'
        },
        {
            type: 'string',
            name: 'mec'
        },
        {
            type: 'int',
            name: 'god'
        },
        {
            type: 'string',
            name: 'boss'
        },
        {
            type: 'string',
            name: 'glavbuh'
        },
        {
            type: 'int',
            name: 'pr'
        },
        {
            type: 'int',
            name: 'usluga_id'
        },
        {
            type: 'string',
            name: 'usluga'
        },
        {
            type: 'int',
            name: 'osmd_id'
        },
        {
            name: 'address_id'
        },
        {
            name: 'lgotnik_id'
        },
        {
            type: 'string',
            name: 'fio'
        },
        {
            type: 'float',
            name: 'zadol'
        },
        {
            type: 'float',
            name: 'dolg'
        },
        {
            type: 'float',
            name: 'tarif'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'string',
            name: 'inn'
        },
        {
            type: 'float',
            name: 'poplata'
        },
        {
            type: 'float',
            name: 'norma'
        },
        {
            type: 'float',
            name: 'perer'
        }
    ]
});