/*
 * File: app/view/flat/TabAppTeplomer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.view.flat.TabAppTeplomer', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabappteplomer',

    requires: [
        'Osbb.view.flat.TabAppTeplomerViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Action',
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox'
    ],

    viewModel: {
        type: 'tabappteplomer'
    },
    id: 'tabAppTeplomer',
    layout: 'fit',
    title: 'Тепломеры',

    items: [
        {
            xtype: 'form',
            id: 'fmAppTeplomer',
            scrollable: true,
            bodyPadding: 10,
            icon: '',
            title: '',
            items: [
                {
                    xtype: 'panel',
                    width: 930,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            margin: '0 5 0 0',
                            width: 555,
                            collapsed: true,
                            collapsible: true,
                            title: 'Льготники по квартире',
                            emptyText: 'Льготников нет',
                            store: 'StLgotnik',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 135,
                                    dataIndex: 'fio',
                                    menuDisabled: true,
                                    text: 'Ф.И.О'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 135,
                                    dataIndex: 'lgota',
                                    menuDisabled: true,
                                    text: 'льгота'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 45,
                                    dataIndex: 'people',
                                    menuDisabled: true,
                                    text: 'чел',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 40,
                                    dataIndex: 'percent',
                                    menuDisabled: true,
                                    text: '%'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 45,
                                    dataIndex: 'gr',
                                    menuDisabled: true,
                                    text: 'гр',
                                    format: '0'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 85,
                                    dataIndex: 'fdate',
                                    menuDisabled: true,
                                    text: 'дата'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 45,
                                    dataIndex: 'vkl',
                                    menuDisabled: true,
                                    text: 'вкл'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            height: 118,
                            id: 'grAppHTeplomer',
                            width: 367,
                            collapsed: true,
                            collapsible: true,
                            title: 'Тепломеры снятые с учета',
                            store: 'StHTeplomer',
                            viewConfig: {
                                height: 51
                            },
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    width: 63,
                                    dataIndex: 'teplomer_id',
                                    menuDisabled: true,
                                    text: 'Ид',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 145,
                                    dataIndex: 'model',
                                    menuDisabled: true,
                                    text: 'Модель'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 100,
                                    dataIndex: 'nomer',
                                    menuDisabled: true,
                                    text: 'Номер'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 80,
                                    dataIndex: 'data_spis',
                                    menuDisabled: true,
                                    text: 'Списан'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 35,
                                    menuDisabled: true,
                                    icon: 'resources/css/images/ico/no.png',
                                    iconCls: '',
                                    items: [
                                        {

                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: 930,
                    layout: {
                        type: 'hbox',
                        align: 'stretchmax'
                    }
                },
                {
                    xtype: 'fieldset',
                    height: 295,
                    margin: '5 0 5 0',
                    style: 'background-color: #DCDCDC;',
                    width: 930,
                    layout: 'absolute',
                    title: 'Текущее показание квартирного тепломера',
                    items: [
                        {
                            xtype: 'button',
                            x: 60,
                            y: 10,
                            formBind: false,
                            height: 25,
                            id: 'addAppTeplomer',
                            width: 185,
                            icon: 'resources/css/images/ico/add.png',
                            text: 'добавить тепломер'
                        },
                        {
                            xtype: 'gridpanel',
                            x: 0,
                            y: 40,
                            height: 125,
                            id: 'grAppTeplomer',
                            width: 340,
                            title: 'Приборы учета',
                            store: 'StTeplomer',
                            columns: [
                                {
                                    xtype: 'actioncolumn',
                                    width: 30,
                                    menuDisabled: true,
                                    items: [
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                metaData = 'x-grid-center-icon';
                                                return metaData;
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                Ext.MessageBox.confirm({
                                                    title: 'Замена тепломера',
                                                    msg: 'Вы заменяете тепломер. <br>Подтвердите или отмените свои действия.',
                                                    buttons: Ext.MessageBox.OKCANCEL,
                                                    icon: Ext.MessageBox.ERROR,
                                                    buttonText:{
                                                        ok:'подтвеждаю',
                                                        cancel:'отмена'
                                                    },
                                                    fn:function(btn,newValue){
                                                        if(btn=='ok'){
                                                            var winAddTeplomer = Ext.ClassManager.instantiateByAlias('widget.winaddteplomer');
                                                            var form = winAddTeplomer.down('#fmAddTeplomer');
                                                            //    var check = form.down('#chkExistentVod');
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var values =stUser.getAt(0);
                                                            var value = record;//stVodomer.getAt(rowIndex).data;
                                                            //LOGIKA'
                                                            view.getSelectionModel().select(rowIndex);
                                                            values.set({'vibor':'changeAppTeplomer','rowind':rowIndex});
                                                            stUser.sync();
                                                            form.down('#btAddTeplomer').setText('Заменить тепломер');
                                                            //  check.hide();
                                                            form.loadRecord(value);
                                                            form.doLayout();
                                                            winAddTeplomer.setTitle('Замена тепломера');
                                                            winAddTeplomer.show();
                                                        }
                                                    }
                                                });
                                            },
                                            icon: 'resources/css/images/ico/no.png',
                                            tooltip: 'Удалить тепломер в историю'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.get('out')===1){
                                            metaData.tdCls = 'line-through';
                                        }
                                        return value;
                                    },
                                    width: 135,
                                    dataIndex: 'model',
                                    menuDisabled: true,
                                    text: 'Модель'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.get('out')===1){
                                            metaData.tdCls = 'line-through';
                                        }
                                        return value;
                                    },
                                    width: 100,
                                    dataIndex: 'nomer',
                                    menuDisabled: true,
                                    text: 'Номер'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 30,
                                    menuDisabled: true,
                                    items: [
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                metaData = 'x-grid-center-icon';
                                                return metaData;
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                Ext.MessageBox.confirm({
                                                    title: 'Обновление данных по  тепломеру',
                                                    msg: 'Вы обновляете данные по  тепломеру. <br>Подтвердите или отмените свои действия.',
                                                    buttons: Ext.MessageBox.OKCANCEL,
                                                    icon: Ext.MessageBox.ERROR,
                                                    buttonText:{
                                                        ok:'подтвеждаю',
                                                        cancel:'отмена'
                                                    },
                                                    fn:function(btn,newValue){
                                                        if(btn=='ok'){
                                                            var fmAppTeplomer = Ext.getCmp('fmAppTeplomer');
                                                            var tek = fmAppTeplomer.getForm().findField('tek').getValue();
                                                            //     var pdate = fmAppTeplomer.getForm().findField('pdate').getValue();
                                                            //     var sdate = fmAppTeplomer.getForm().findField('sdate').getValue();

                                                            var winAddTeplomer = Ext.ClassManager.instantiateByAlias('widget.winaddteplomer');
                                                            var form = winAddTeplomer.down('#fmAddTeplomer');
                                                            //    var check = form.down('#chkExistentVod');
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var values =stUser.getAt(0);
                                                            var value = record;
                                                            //LOGIKA'
                                                            view.getSelectionModel().select(rowIndex);
                                                            values.set({'vibor':'editAppTeplomer','rowind':rowIndex});
                                                            stUser.sync();
                                                            form.down('#btAddTeplomer').setText('Обновить тепломер');
                                                            form.getForm().findField('tek').setFieldLabel('Текущие показания');

                                                            //  check.hide();
                                                            form.loadRecord(value);
                                                            form.getForm().findField('tek').setValue(tek);
                                                            //    form.getForm().findField('pdate').setValue(pdate);
                                                            //    form.getForm().findField('sdate').setValue(sdate);

                                                            winAddTeplomer.setTitle('Обновление данных по  тепломеру');
                                                            winAddTeplomer.show();
                                                        }
                                                    }
                                                });
                                            },
                                            icon: 'resources/css/images/ico/edit.png',
                                            tooltip: 'Обновить данные по водомеру'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'actioncolumn',
                                    width: 30,
                                    menuDisabled: true,
                                    icon: 'resources/css/images/ico/no.png',
                                    items: [
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                var out = r.get('out');
                                                if (out === 0 ) {
                                                    metaData = 'x-hide-display';
                                                } else if (out === 1   ){
                                                    metaData = 'x-grid-center-icon';
                                                }
                                                return metaData;
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                // in use
                                                var me = this;
                                                //STORE
                                                var stUser = Ext.data.StoreManager.get("StUser");
                                                var StAllPokTeplomera = Ext.data.StoreManager.get("StAllPokTeplomera");//QueryTeplomer.getResults  <AllPokDTeplomera>
                                                var StTekPokTeplomera = Ext.data.StoreManager.get("StTekPokTeplomera");//QueryTeplomer.getResults <TekPokDTeplomera>
                                                var StTeplomer = view.getStore();
                                                //LOGIN & PASSWORD

                                                var values =stUser.getAt(0);
                                                var params = {
                                                    login:values.get('login'),
                                                    password:values.get('password'),
                                                    house_id:values.get('house_id'),
                                                    address_id:values.get('address_id'),
                                                    what:"ATeplomer"
                                                };
                                                //GRID

                                                var value = StTeplomer.getAt(rowIndex).data;

                                                //FORMA

                                                var fmAppteplomers = Ext.getCmp('fmAppTeplomer');

                                                //LOGIKA

                                                Ext.Object.merge(value, params);
                                                //console.log(value);

                                                Ext.MessageBox.confirm({
                                                    title: 'Возвращение  тепломера из поверки',
                                                    msg: 'Вы возвращаете тепломер с поверки <br>Подтвердите или отмените свои действия.',
                                                    buttons: Ext.MessageBox.OKCANCEL,
                                                    icon: Ext.MessageBox.ERROR,
                                                    buttonText:{
                                                        ok:'подтвеждаю',
                                                        cancel:'отмена'
                                                    },
                                                    fn:function(btn,newValue){
                                                        if(btn=='ok'){
                                                            QueryTeplomer.outTeplomerHistory(value,function(results){
                                                                if (results.success){
                                                                    StAllPokTeplomera.removeAll();
                                                                    StTeplomer.removeAll();
                                                                    StTekPokTeplomera.removeAll();
                                                                    StTeplomer.load({
                                                                        params: {
                                                                            what:'AppTeplomer',
                                                                            address_id: value.address_id,
                                                                            login:value.login,
                                                                            password:value.password
                                                                        },
                                                                        scope:this
                                                                    });
                                                                    //StTeplomer.sync();
                                                                    view.refresh();
                                                                    fmAppteplomers.getForm().reset();

                                                                    setTimeout(function(){
                                                                        Ext.MessageBox.show({
                                                                            title: 'Возвращение тепломера из поверки',
                                                                            msg: results.msg,
                                                                            buttons: Ext.MessageBox.OK,
                                                                            icon: Ext.MessageBox.INFO
                                                                        });
                                                                    }, 500);

                                                                }
                                                            });
                                                        }
                                                    }
                                                });
                                            },
                                            icon: 'resources/css/images/ico/door_out.png',
                                            tooltip: 'Вернуть тепломер из поверки'
                                        },
                                        {
                                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                //console.log(r);
                                                var out = r.get('out');
                                                //console.log(out);
                                                if (out === 1 ) {
                                                    metaData = 'x-hide-display';
                                                    //console.log(1);
                                                } else if (out === 0   ){
                                                    metaData = 'x-grid-center-icon';
                                                    // console.log(0);
                                                }
                                                return metaData;
                                            },
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                // in use
                                                var me = this;
                                                //STORE
                                                var stUser = Ext.data.StoreManager.get("StUser");
                                                var StTeplomer = view.getStore();
                                                //LOGIN & PASSWORD

                                                var values =stUser.getAt(0);
                                                var params = {
                                                    login:values.get('login'),
                                                    password:values.get('password'),
                                                    house_id:values.get('house_id'),
                                                    address_id:values.get('address_id'),
                                                    what:"ATeplomer"
                                                };
                                                //GRID

                                                var value = StTeplomer.getAt(rowIndex).data;

                                                //FORMA
                                                var fmAppTeplomer = Ext.getCmp('fmAppTeplomer');
                                                //LOGIKA
                                                Ext.Object.merge(value, params);
                                                //console.log(value);

                                                Ext.MessageBox.confirm({
                                                    title: 'Вывод квартирного тепломера в поверку',
                                                    msg: 'Вы выводите тепломер в поверку <br>Подтвердите или отмените свои действия.',
                                                    buttons: Ext.MessageBox.OKCANCEL,
                                                    icon: Ext.MessageBox.ERROR,
                                                    buttonText:{
                                                        ok:'подтвеждаю',
                                                        cancel:'отмена'
                                                    },
                                                    fn:function(btn,newValue){
                                                        if(btn=='ok'){
                                                            QueryTeplomer.inTeplomerHistory(value,function(results){
                                                                if (results.success){
                                                                    StTeplomer.removeAll();
                                                                    StTeplomer.load({
                                                                        params: {
                                                                            what:'AppTeplomer',
                                                                            house_id: value.house_id,
                                                                            login:value.login,
                                                                            password:value.password,
                                                                            address_id:value.address_id
                                                                        },
                                                                        scope:this
                                                                    });
                                                                    //StTeplomer.sync();
                                                                    view.refresh();
                                                                    fmAppTeplomer.getForm().reset();

                                                                    setTimeout(function(){
                                                                        Ext.MessageBox.show({
                                                                            title: 'Вывод  тепломера в поверку',
                                                                            msg: results.msg,
                                                                            buttons: Ext.MessageBox.OK,
                                                                            icon: Ext.MessageBox.INFO
                                                                        });
                                                                    }, 500);
                                                                }
                                                            });
                                                        }
                                                    }
                                                });


                                            },
                                            icon: 'resources/css/images/ico/maintenance_16.png',
                                            tooltip: 'Вывод тепломера на поверку'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 730,
                            y: 10,
                            height: 255,
                            style: 'background-color: #F1EEEE ;',
                            width: 175,
                            title: 'начислено',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 145,
                                    fieldLabel: 'Гкал/м&sup2;',
                                    labelWidth: 50,
                                    name: 'gkm2',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 145,
                                    fieldLabel: 'Тариф',
                                    labelWidth: 50,
                                    name: 'tarif',
                                    readOnly: true,
                                    decimalPrecision: 3
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 145,
                                    fieldLabel: 'S (м&sup2;)',
                                    labelWidth: 50,
                                    name: 'area',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 145,
                                    fieldLabel: 'отопл',
                                    labelWidth: 50,
                                    name: 'otoplenie',
                                    readOnly: true
                                },
                                {
                                    xtype: 'fieldset',
                                    anchor: '100%',
                                    height: 90,
                                    style: 'background-color: #DCDCDC;',
                                    width: 150,
                                    title: 'Бюджет',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            width: 125,
                                            fieldLabel: 'S льг (м&sup2;)',
                                            labelWidth: 65,
                                            name: 'area_lg',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            width: 125,
                                            fieldLabel: 'Бюджет',
                                            labelWidth: 50,
                                            name: 'budjet',
                                            readOnly: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 560,
                            y: 10,
                            height: 255,
                            style: 'background-color: #F1EEEE ;',
                            width: 165,
                            title: 'показание',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    id: 'AppT_pok_id',
                                    padding: '0 5 0 5',
                                    width: 140,
                                    fieldLabel: 'ид_пок',
                                    labelWidth: 50,
                                    name: 'pok_id',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 140,
                                    fieldLabel: 'Дата',
                                    labelWidth: 50,
                                    name: 'fdate',
                                    readOnly: true,
                                    altFormats: 'd-m-Y|m/d/Y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y|m-d-y|m-d-Y|m/d|m-d|md|mdy|mdY|d|Y-m-d|n-j|n/j',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 140,
                                    fieldLabel: 'пред',
                                    labelWidth: 50,
                                    name: 'pred',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 140,
                                    fieldLabel: 'К-во',
                                    labelWidth: 50,
                                    name: 'qty',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 140,
                                    fieldLabel: 'Гкал',
                                    labelWidth: 50,
                                    name: 'gkal',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 140,
                                    fieldLabel: 'текущ',
                                    labelWidth: 50,
                                    name: 'tekp',
                                    hideTrigger: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'button',
                                    anchor: '100%',
                                    formBind: true,
                                    id: 'delTekPokAppTeplomera',
                                    width: 163,
                                    icon: 'resources/css/images/ico/no.png',
                                    text: 'Удалить показ'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 345,
                            y: 10,
                            height: 255,
                            style: 'background-color: #F1EEEE ;',
                            width: 205,
                            title: 'Техническая  характеристика',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'fmAppTeplomer_id',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'тепломер',
                                    labelWidth: 80,
                                    name: 'teplomer_id',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    style: '{color: #378005; text-shadow: -1px -1px white, 1px 1px #333;font-size:14pt;}',
                                    width: 160,
                                    fieldLabel: '',
                                    name: 'model',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Номер',
                                    labelWidth: 80,
                                    name: 'nomer',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Дтеплом',
                                    labelWidth: 80,
                                    name: 'dteplomer_id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    height: 20,
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Ед.изм',
                                    labelWidth: 80,
                                    name: 'edizm',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    height: 20,
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Коеф',
                                    labelWidth: 80,
                                    name: 'koef',
                                    readOnly: true,
                                    decimalPrecision: 5
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 183,
                                    fieldLabel: 'Дата ввода',
                                    labelWidth: 90,
                                    name: 'sdate',
                                    readOnly: true,
                                    altFormats: 'd-m-Y|m/d/Y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y|m-d-y|m-d-Y|m/d|m-d|md|mdy|mdY|d|Y-m-d|n-j|n/j',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    width: 183,
                                    fieldLabel: 'Дата поверки',
                                    labelWidth: 90,
                                    name: 'pdate',
                                    readOnly: true,
                                    altFormats: 'd-m-Y|m/d/Y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y|m-d-y|m-d-Y|m/d|m-d|md|mdy|mdY|d|Y-m-d|n-j|n/j',
                                    format: 'd-m-Y',
                                    submitFormat: 'Y-m-d'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 5,
                            y: 175,
                            height: 90,
                            style: 'background-color: #F1EEEE ;',
                            width: 330,
                            layout: 'absolute',
                            title: 'Ввод новых показаний',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    x: 0,
                                    y: 0,
                                    width: 155,
                                    fieldLabel: 'текущее',
                                    labelWidth: 60,
                                    name: 'tek',
                                    hideTrigger: true,
                                    autoStripChars: true,
                                    decimalPrecision: 3
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 0,
                                    y: 35,
                                    formBind: false,
                                    shadowOffset: 1,
                                    id: 'newPokAppTepl',
                                    width: 155,
                                    fieldLabel: 'новое',
                                    labelWidth: 60,
                                    name: 'newValue',
                                    value: 0,
                                    allowBlank: false,
                                    hideTrigger: true,
                                    selectOnFocus: true,
                                    autoStripChars: true,
                                    decimalPrecision: 3,
                                    minValue: 0,
                                    negativeText: 'Значение должно быть больше 1'
                                },
                                {
                                    xtype: 'button',
                                    x: 165,
                                    y: 35,
                                    formBind: true,
                                    shadowOffset: 2,
                                    id: 'insTekPokAppTeplomer',
                                    width: 140,
                                    icon: 'resources/css/images/ico/yes22.png',
                                    text: 'Записать'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 165,
                                    y: 0,
                                    width: 160,
                                    fieldLabel: 'за пред. месяц',
                                    labelWidth: 120,
                                    name: 'prev',
                                    boxLabel: '',
                                    inputValue: '1'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    id: 'grAllPokAppTeplomera',
                    margin: '5 0 0 0',
                    width: 930,
                    collapsible: true,
                    title: 'История показаний тепломера',
                    store: 'StAllPokTeplomera',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'показания',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 85,
                                    dataIndex: 'data',
                                    menuDisabled: true,
                                    text: 'дата',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 81,
                                    dataIndex: 'pred',
                                    menuDisabled: true,
                                    text: 'пред',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 73,
                                    dataIndex: 'tek',
                                    menuDisabled: true,
                                    text: 'тек',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 73,
                                    dataIndex: 'qty',
                                    menuDisabled: true,
                                    text: 'кол-во',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 72,
                                    dataIndex: 'gkal',
                                    menuDisabled: true,
                                    text: 'Гкалл',
                                    format: '0.000000'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Параметры',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 67,
                                    dataIndex: 'edizm',
                                    menuDisabled: true,
                                    text: 'ед.изм'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 79,
                                    dataIndex: 'koef',
                                    menuDisabled: true,
                                    text: 'коэф',
                                    format: '0.00000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 63,
                                    dataIndex: 'area',
                                    menuDisabled: true,
                                    text: 'S (м&sup2;)',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 84,
                                    dataIndex: 'temp',
                                    menuDisabled: true,
                                    text: 'Гкал/м2',
                                    format: '0.000000'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Бюджет',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    width: 70,
                                    dataIndex: 'area_lg',
                                    menuDisabled: true,
                                    text: 'S (м&sup2;)',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 88,
                                    dataIndex: 'budjet',
                                    menuDisabled: true,
                                    text: 'льгота',
                                    format: '0.000'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 90,
                            dataIndex: 'operator',
                            menuDisabled: true,
                            text: 'оператор'
                        }
                    ]
                }
            ]
        }
    ]

});