/*
 * File: app/view/sprav/TabDbfLgotaViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.view.sprav.TabDbfLgotaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabdbflgota',

    onComboboxSelect211: function(combo, record, eOpts) {
        var stUser = Ext.data.StoreManager.get("StUser");
        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');
        var usluga_id = values.get('usluga_id');
        var dataNach = Ext.getCmp('dataNachLgota');
        var data = dataNach.getValue();
        var stSubsidia = Ext.data.StoreManager.get("StDbfLgota");

        var btnGetSubsidiaOshadBank =  Ext.getCmp('btnGetLgotaOshadBank');
        var btnPrintLgotaReestrToOshadBank =  Ext.getCmp('btnPrintLgotaReestrToOshadBank');
        var btnPrintLgotaReestrFromOshadBank =  Ext.getCmp('btnPrintLgotaReestrFromOshadBank');
        var btnImportOshadBank =  Ext.getCmp('btnImportOshadBankLgota');
        var btnExportOshadBank =  Ext.getCmp('btnExportOshadBankLgota');
        var btnImportOplataOshad =  Ext.getCmp('btnImportOplataOshadLgota');
        var btnImportOplataYkis =  Ext.getCmp('btnImportOplataYkisLgota');
        var btnSubsidiaOtkat =  Ext.getCmp('btnLgotaOtkat');
        var osmd_id = Ext.getCmp('cbOsmdLgota').getValue();


        if(osmd_id) {
            values.set({'usluga_id':record.get('usluga_id')});
            stUser.sync();
            btnGetSubsidiaOshadBank.setDisabled(false);
            btnPrintLgotaReestrToOshadBank.setDisabled(false);
            btnPrintLgotaReestrFromOshadBank.setDisabled(false);
            btnImportOshadBank.setDisabled(false);
            btnExportOshadBank.setDisabled(false);
            btnImportOplataYkis.setDisabled(false);
            btnImportOplataOshad.setDisabled(false);
            btnSubsidiaOtkat.setDisabled(false);


            stSubsidia.load({
                params: {
                    what:'getDbfLgota',
                    login:login,
                    password:password,
                    data:data,
                    usluga_id:record.get('usluga_id'),
                    osmd_id:osmd_id

                },
                scope:this
            });
        }else{
            btnGetSubsidiaOshadBank.setDisabled(true);
            btnPrintLgotaReestrToOshadBank.setDisabled(true);
            btnPrintLgotaReestrFromOshadBank.setDisabled(true);
            btnImportOshadBank.setDisabled(true);
            btnExportOshadBank.setDisabled(true);
            btnImportOplataOshad.setDisabled(true);
            btnImportOplataYkis.setDisabled(true);
            btnSubsidiaOtkat.setDisabled(true);

        }
    }

});
