/*
 * File: app/view/sprav/TabKvartplata.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.view.sprav.TabKvartplata', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabkvartplata',

    requires: [
        'Osbb.view.sprav.TabKvartplataViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.panel.Tool',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'tabkvartplata'
    },
    id: 'tabKvartplata',
    scrollable: true,
    width: 933,
    layout: 'fit',
    bodyBorder: false,
    closable: true,
    title: 'Квартплата',
    defaultListenerScope: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        id: 'fmKvartplata',
                        scrollable: true,
                        title: '',
                        items: [
                            {
                                xtype: 'gridpanel',
                                id: 'grTarifHousesKv',
                                padding: 10,
                                scrollable: true,
                                width: 916,
                                bodyBorder: true,
                                title: 'Дома',
                                store: 'StTarif',
                                viewConfig: {
                                    getRowClass: function(record, rowIndex, rowParams, store) {
                                        if(record.get('pr_kv') === 0 ){
                                            return 'change_color_yellow';

                                        } else  {
                                            return  'change_color_green';
                                        }
                                    }
                                },
                                dockedItems: [
                                    {
                                        xtype: 'toolbar',
                                        dock: 'top',
                                        items: [
                                            {
                                                xtype: 'combobox',
                                                width: 220,
                                                fieldLabel: 'Дом',
                                                labelWidth: 45,
                                                name: 'id_house',
                                                displayField: 'house',
                                                queryMode: 'local',
                                                store: 'StHousesOrg',
                                                valueField: 'house_id',
                                                listeners: {
                                                    select: 'onComboboxSelect211'
                                                }
                                            },
                                            {
                                                xtype: 'combobox',
                                                id: 'cbTarifKv',
                                                width: 220,
                                                fieldLabel: 'услуга',
                                                labelWidth: 50,
                                                name: 'viborTarif',
                                                displayField: 'usluga',
                                                queryMode: 'local',
                                                store: 'StKvTarif',
                                                valueField: 'tarif',
                                                listeners: {
                                                    select: 'onCbTarifKvSelect'
                                                }
                                            },
                                            {
                                                xtype: 'numberfield',
                                                id: 'tarKv',
                                                width: 200,
                                                fieldLabel: 'значение',
                                                labelWidth: 80,
                                                name: 'tar',
                                                value: 0,
                                                fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
                                                hideTrigger: true,
                                                decimalPrecision: 3
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    var form = button.findParentByType('form');
                                                    var  id_house = form.getForm().findField('id_house').getValue();
                                                    var StTarif = Ext.data.StoreManager.get("StTarif");

                                                    //console.log(id_house);

                                                    var btnInsTarif = Ext.getCmp('btnInsTarifKv');
                                                    var tarif = Ext.getCmp('tarKv');
                                                    var viborTarif = Ext.getCmp('cbTarifKv');
                                                    var stUser = Ext.data.StoreManager.get("StUser");
                                                    var StTarif = Ext.data.StoreManager.get("StTarif");
                                                    var grid =  Ext.getCmp('grTarifHousesKv');
                                                    var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
                                                    var size = Ext.Object.getSize(gridRowSelectedRecords) ;
                                                    var values =stUser.getAt(0);
                                                    var login = values.get('login');
                                                    var password = values.get('password');
                                                    var myMask= Ext.Msg.show({
                                                        title:'Тариф...',
                                                        msg: 'Изменение тарифа.Ожидайте...',
                                                        buttons: Ext.Msg.CANCEL,
                                                        wait: true,
                                                        modal: true,
                                                        icon: Ext.Msg.INFO
                                                    });
                                                    var params =[];
                                                    if (size >= 1){
                                                        params = {
                                                            login:values.get('login'),
                                                            password:values.get('password'),
                                                            what:"vvod_tarif_kv",
                                                            name_tar:viborTarif.getValue(),
                                                            new_tar:tarif.getValue()
                                                        };
                                                        Ext.Object.each(gridRowSelectedRecords, function(key, val, myself) {
                                                            Ext.Object.merge(val.data, params);
                                                            QueryAddress.updateRecords(val.data,function(results){
                                                                if(results.res){
                                                                    return  true;
                                                                }  else {
                                                                    return  false;
                                                                }
                                                            });

                                                        });
                                                        if(id_house == "188"){
                                                            StTarif.load({
                                                                params: {
                                                                    what:'TarifFromHouses',
                                                                    login:login,
                                                                    password:password
                                                                    //data:data,
                                                                    //house_id: record.get('house_id')
                                                                },
                                                                callback: function(records,operation,success){
                                                                    if(success){
                                                                        viborTarif.clearValue();
                                                                        viborTarif.setDisabled(true);
                                                                        tarif.setValue(0);
                                                                        tarif.setDisabled(true);
                                                                        btnInsTarif.setDisabled(true);

                                                                    }
                                                                },
                                                                scope:this
                                                            });
                                                        } else {

                                                            StTarif.load({
                                                                params: {
                                                                    what:'TarifFromHouse',
                                                                    login:login,
                                                                    password:password,
                                                                    //data:data,
                                                                    house_id: id_house
                                                                },
                                                                callback: function(records,operation,success){
                                                                    if(success){
                                                                        viborTarif.clearValue();
                                                                        viborTarif.setDisabled(true);
                                                                        tarif.setValue(0);
                                                                    }
                                                                },
                                                                scope:this
                                                            });
                                                        }
                                                        myMask.close();
                                                    } else {
                                                        myMask.close();
                                                        Ext.MessageBox.show({
                                                            title: 'Ошибка ',
                                                            msg: 'Не выбраны дома  для начисления',
                                                            buttons: Ext.MessageBox.OK,
                                                            icon: Ext.MessageBox.ERROR
                                                        });
                                                    }

                                                },
                                                disabled: true,
                                                id: 'btnInsTarifKv',
                                                width: 135,
                                                icon: 'resources/css/images/ico/yes.png',
                                                text: 'Записать '
                                            }
                                        ]
                                    }
                                ],
                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                    selType: 'checkboxmodel',
                                    showHeaderCheckbox: true
                                }),
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Дом',
                                        columns: [
                                            {
                                                xtype: 'numbercolumn',
                                                width: 43,
                                                dataIndex: 'house_id',
                                                menuDisabled: true,
                                                text: 'ид',
                                                format: '0'
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                width: 80,
                                                align: 'center',
                                                dataIndex: 'data',
                                                menuDisabled: true,
                                                text: 'дата',
                                                format: 'F,y'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                width: 152,
                                                dataIndex: 'house',
                                                menuDisabled: true,
                                                text: 'Дом'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                width: 35,
                                                dataIndex: 'floor',
                                                menuDisabled: true,
                                                text: 'Эт',
                                                format: '0'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Квартплата дома',
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                text: '1 этаж',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 60,
                                                        align: 'center',
                                                        dataIndex: 'kvf1',
                                                        menuDisabled: true,
                                                        text: 'Тар',
                                                        format: '0.000'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 55,
                                                        align: 'center',
                                                        dataIndex: 'ch_kvf1',
                                                        menuDisabled: true,
                                                        text: 'Пер',
                                                        format: '0.000'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                text: '2й и выше',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 60,
                                                        align: 'center',
                                                        dataIndex: 'kv',
                                                        menuDisabled: true,
                                                        text: 'Тар',
                                                        format: '0.000'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 55,
                                                        align: 'center',
                                                        dataIndex: 'ch_kv',
                                                        menuDisabled: true,
                                                        text: 'Пер',
                                                        format: '0.000'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Тариф для льготников',
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                text: '1 этаж',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 82,
                                                        align: 'center',
                                                        dataIndex: 'lgf1',
                                                        menuDisabled: true,
                                                        text: 'Тар',
                                                        format: '0.000'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                text: '2й и выше',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 87,
                                                        align: 'center',
                                                        dataIndex: 'lg',
                                                        menuDisabled: true,
                                                        text: 'Тар',
                                                        format: '0.000'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'raion',
                                        text: 'Raion'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        width: 55,
                                        align: 'center',
                                        dataIndex: 'dop',
                                        menuDisabled: true,
                                        text: 'Доп',
                                        format: '0.000'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        width: 56,
                                        dataIndex: 'remont',
                                        menuDisabled: true,
                                        text: 'Рем',
                                        format: '0.00'
                                    }
                                ],
                                tools: [
                                    {
                                        xtype: 'tool',
                                        callback: function(owner, tool, event) {
                                            //STORE
                                            var stUser = Ext.data.StoreManager.get("StUser");
                                            var StTarif = Ext.data.StoreManager.get("StTarif");
                                            //LOGIN & PASSWORD
                                            var values =stUser.getAt(0);
                                            var login = values.get('login');
                                            var password = values.get('password');
                                            // FORM
                                            var tarif = Ext.getCmp('tarKv');
                                            var viborTarif = Ext.getCmp('cbTarifKv');
                                            var form = tool.findParentByType('form');
                                            var value = form.getValues();

                                            StTarif.load({
                                                params: {
                                                    what:'TarifFromHouseAll',
                                                    login:login,
                                                    password:password,
                                                    house_id: value.id_house
                                                },
                                                callback: function(records,operation,success){
                                                    if(success){
                                                        viborTarif.clearValue();
                                                        viborTarif.setDisabled(true);
                                                        tarif.setValue(0);
                                                    }
                                                },
                                                scope:this
                                            });

                                        },
                                        type: 'search'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                height: 516,
                                padding: 10,
                                width: 920,
                                layout: 'absolute',
                                animCollapse: true,
                                title: 'Начисление и перерасчет по кварплате',
                                titleCollapse: true,
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        height: 450,
                                        padding: '',
                                        style: 'background-color: #DCDCDC;',
                                        width: 890,
                                        layout: 'absolute',
                                        title: '',
                                        items: [
                                            {
                                                xtype: 'datefield',
                                                x: 40,
                                                y: 15,
                                                style: 'background-color: #F1EEEE ;',
                                                width: 270,
                                                fieldLabel: 'Период начисления ',
                                                labelWidth: 130,
                                                name: 'data_nach',
                                                readOnly: true,
                                                format: 'F,Y',
                                                startDay: 1,
                                                submitFormat: 'Ymd'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, e) {
                                                    var stUser = Ext.data.StoreManager.get("StUser");
                                                    var grid =  Ext.getCmp('grTarifHousesKv');
                                                    var value = button.findParentByType('form').getValues();
                                                    var StTarif = Ext.data.StoreManager.get("StTarif");

                                                    var house_id = value.id_house;

                                                    var values =stUser.getAt(0);
                                                    var params = {
                                                        login:values.get('login'),
                                                        password:values.get('password'),
                                                        what:"nachislenie_kvartplata_now",
                                                        house_id:house_id
                                                    };


                                                    var myMask= Ext.Msg.show({
                                                        title:'Начисление...',
                                                        msg: 'Начисление квартплаты .Ожидайте...',
                                                        buttons: Ext.Msg.CANCEL,
                                                        wait: true,
                                                        modal: true,
                                                        icon: Ext.Msg.INFO
                                                    });

                                                    QueryAddress.updateRecords(params,function(results){
                                                        if(results.success==="1"){
                                                            myMask.close();
                                                            Ext.MessageBox.show({
                                                                title: 'Начисление квартплаты',
                                                                msg: results.msg,
                                                                buttons: Ext.MessageBox.OK,
                                                                icon: Ext.MessageBox.INFO
                                                            });

                                                            StTarif.load({
                                                                params: {
                                                                    what:'TarifFromHouse',
                                                                    login:values.get('login'),
                                                                    password:values.get('password'),
                                                                    house_id: house_id
                                                                },
                                                                callback: function(records,operation,success){
                                                                    if(success){

                                                                    }
                                                                },
                                                                scope:this
                                                            });


                                                        } else {
                                                            myMask.close();
                                                            Ext.MessageBox.show({
                                                                title: 'Начисление квартплаты',
                                                                msg: results.msg,
                                                                buttons: Ext.MessageBox.OK,
                                                                icon: Ext.MessageBox.ERROR
                                                            });
                                                        }

                                                    });



                                                },
                                                x: 410,
                                                y: 15,
                                                formBind: false,
                                                disabled: true,
                                                id: 'btAddNachKv',
                                                width: 440,
                                                icon: 'resources/css/images/ico/add.png',
                                                text: 'начислить квартплату за период'
                                            },
                                            {
                                                xtype: 'fieldset',
                                                x: 15,
                                                y: 60,
                                                height: 375,
                                                style: 'background-color: #F1EEEE ;',
                                                width: 835,
                                                layout: 'absolute',
                                                title: 'Перерасчет',
                                                items: [
                                                    {
                                                        xtype: 'checkboxfield',
                                                        x: 5,
                                                        y: 5,
                                                        style: 'background-color: #F1EEEE ;',
                                                        fieldLabel: 'тарифы установлены вручную',
                                                        labelWidth: 250,
                                                        name: 'tarif_manual',
                                                        boxLabel: '',
                                                        inputValue: '1',
                                                        uncheckedValue: '0'
                                                    },
                                                    {
                                                        xtype: 'fieldset',
                                                        x: 10,
                                                        y: 40,
                                                        height: 100,
                                                        style: 'background-color: #DCDCDC;',
                                                        width: 800,
                                                        title: 'дома до 12 этажей',
                                                        layout: {
                                                            type: 'hbox',
                                                            align: 'stretchmax'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'fieldset',
                                                                height: 70,
                                                                width: 379,
                                                                title: '1этаж',
                                                                layout: {
                                                                    type: 'hbox',
                                                                    align: 'stretchmax'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'numberfield',
                                                                        padding: 5,
                                                                        style: 'background-color: #F1EEEE ;',
                                                                        width: 170,
                                                                        fieldLabel: 'действ',
                                                                        labelWidth: 60,
                                                                        name: 'kvf1',
                                                                        hideTrigger: true,
                                                                        decimalPrecision: 3
                                                                    },
                                                                    {
                                                                        xtype: 'numberfield',
                                                                        padding: 5,
                                                                        style: 'background-color: #F1EEEE ;',
                                                                        width: 170,
                                                                        fieldLabel: 'новый',
                                                                        labelWidth: 50,
                                                                        name: 'ch_kvf1',
                                                                        hideTrigger: true,
                                                                        decimalPrecision: 3
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                xtype: 'fieldset',
                                                                width: 385,
                                                                title: '2й этаж и выше',
                                                                layout: {
                                                                    type: 'hbox',
                                                                    align: 'stretchmax'
                                                                },
                                                                items: [
                                                                    {
                                                                        xtype: 'numberfield',
                                                                        padding: 5,
                                                                        style: 'background-color: #F1EEEE ;',
                                                                        width: 170,
                                                                        fieldLabel: 'действ',
                                                                        labelWidth: 50,
                                                                        name: 'kv',
                                                                        hideTrigger: true,
                                                                        decimalPrecision: 3
                                                                    },
                                                                    {
                                                                        xtype: 'numberfield',
                                                                        padding: 5,
                                                                        style: 'background-color: #F1EEEE ;',
                                                                        width: 170,
                                                                        fieldLabel: 'новый',
                                                                        labelWidth: 50,
                                                                        name: 'ch_kv',
                                                                        hideTrigger: true,
                                                                        decimalPrecision: 3
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'textareafield',
                                                        x: 230,
                                                        y: 200,
                                                        height: 70,
                                                        style: 'background-color: #F1EEEE ;',
                                                        width: 390,
                                                        fieldLabel: 'Инфо перер',
                                                        name: 'info'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        handler: function(checkbox, checked) {
                                                            var form = checkbox.findParentByType('form');
                                                            var  address_ot = form.getForm().findField('address_ot');
                                                            var  address_do = form.getForm().findField('address_do');

                                                            if(checked===true){
                                                                if (address_ot.isVisible()) address_ot.hide();
                                                                if (address_do.isVisible()) address_do.hide();
                                                            } else {
                                                                if (address_ot.isHidden()) address_ot.show();
                                                                if (address_do.isHidden()) address_do.show();

                                                            }
                                                        },
                                                        x: 20,
                                                        y: 150,
                                                        style: 'background-color: #F1EEEE ;',
                                                        fieldLabel: 'По всем квартирам дома',
                                                        labelWidth: 200,
                                                        name: 'allkv',
                                                        boxLabel: '',
                                                        checked: true,
                                                        inputValue: '1',
                                                        uncheckedValue: '0'
                                                    },
                                                    {
                                                        xtype: 'fieldset',
                                                        x: 20,
                                                        y: 190,
                                                        height: 85,
                                                        style: 'background-color: #F1EEEE ;',
                                                        width: 195,
                                                        title: 'Период перерасчета',
                                                        items: [
                                                            {
                                                                xtype: 'datefield',
                                                                anchor: '100%',
                                                                width: 185,
                                                                fieldLabel: 'Дата с',
                                                                labelWidth: 60,
                                                                name: 'sdata',
                                                                format: 'd-m-Y',
                                                                submitFormat: 'Ymd'
                                                            },
                                                            {
                                                                xtype: 'datefield',
                                                                anchor: '100%',
                                                                width: 185,
                                                                fieldLabel: 'Дата по',
                                                                labelWidth: 60,
                                                                name: 'fdata',
                                                                format: 'd-m-Y',
                                                                submitFormat: 'Ymd'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        x: 540,
                                                        y: 150,
                                                        hidden: true,
                                                        style: 'background-color: #C2D9E9;',
                                                        width: 220,
                                                        fieldLabel: 'по',
                                                        labelWidth: 20,
                                                        name: 'address_do',
                                                        editable: false,
                                                        displayField: 'address',
                                                        forceSelection: true,
                                                        queryMode: 'local',
                                                        store: 'StAddressOrg',
                                                        valueField: 'address_id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        x: 290,
                                                        y: 150,
                                                        hidden: true,
                                                        style: 'background-color: #C2D9E9;',
                                                        width: 220,
                                                        fieldLabel: 'c',
                                                        labelWidth: 20,
                                                        name: 'address_ot',
                                                        enableKeyEvents: true,
                                                        displayField: 'address',
                                                        forceSelection: true,
                                                        queryMode: 'local',
                                                        store: 'StAddressOrg',
                                                        valueField: 'address_id'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        handler: function(button, e) {
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var grid =  Ext.getCmp('grTarifHousesKv');
                                                            var value = button.findParentByType('form').getValues();
                                                            var getRowSelection = grid.getSelectionModel().getSelection()[0];
                                                            var house_id = getRowSelection.get('house_id');
                                                            //console.log(value);

                                                            var values =stUser.getAt(0);
                                                            var params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"pereraschet_kvartplata",
                                                                house_id:house_id
                                                            };

                                                            params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"pereraschet_kvartplata",
                                                                house_id:house_id,
                                                                kvf1:value.kvf1,
                                                                kv:value.kv,
                                                                ch_kvf1:value.ch_kvf1,
                                                                ch_kv:value.ch_kv,
                                                                allkv:value.allkv,
                                                                tarif_manual:value.tarif_manual,
                                                                sdata:value.sdata,
                                                                fdata:value.fdata,
                                                                address_ot:value.address_ot,
                                                                address_do:value.address_do,
                                                                info:value.info
                                                            };
                                                            //console.log(params);

                                                            var myMask= Ext.Msg.show({
                                                                title:'Перерасчет...',
                                                                msg: 'Перерасчет квартплаты .Ожидайте...',
                                                                buttons: Ext.Msg.CANCEL,
                                                                wait: true,
                                                                modal: true,
                                                                icon: Ext.Msg.INFO
                                                            });

                                                            QueryAddress.updateRecords(params,function(results){
                                                                if(results.success==="1"){
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Перерасчет квартплаты',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.INFO
                                                                    });
                                                                } else {
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Перерасчет квартплаты',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.ERROR
                                                                    });
                                                                }

                                                            });





                                                        },
                                                        x: 460,
                                                        y: 290,
                                                        disabled: true,
                                                        height: 30,
                                                        id: 'btAddPererKv',
                                                        width: 340,
                                                        icon: 'resources/css/images/ico/add.png',
                                                        text: 'Перерасчитать квартплату за период'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        handler: function(button, e) {
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var grid =  Ext.getCmp('grTarifHousesKv');
                                                            var value = button.findParentByType('form').getValues();
                                                            var getRowSelection = grid.getSelectionModel().getSelection()[0];
                                                            var house_id = getRowSelection.get('house_id');
                                                            //console.log(value);

                                                            var values =stUser.getAt(0);
                                                            var params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"nachislenie_dop_osbb",
                                                                house_id:house_id
                                                            };

                                                            params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"nachislenie_dop_osbb",
                                                                house_id:house_id,
                                                                allkv:value.allkv,
                                                                sdata:value.sdata,
                                                                fdata:value.fdata,
                                                                address_ot:value.address_ot,
                                                                address_do:value.address_do,
                                                                info:value.info
                                                            };
                                                            //console.log(params);

                                                            var myMask= Ext.Msg.show({
                                                                title:'Начисление услуги...',
                                                                msg: 'Начисление услуги .Ожидайте...',
                                                                buttons: Ext.Msg.CANCEL,
                                                                wait: true,
                                                                modal: true,
                                                                icon: Ext.Msg.INFO
                                                            });

                                                            QueryAddress.updateRecords(params,function(results){
                                                                if(results.success==="1"){
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Начисление услуги',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.INFO
                                                                    });
                                                                } else {
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Начисление услуги',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.ERROR
                                                                    });
                                                                }

                                                            });





                                                        },
                                                        x: 630,
                                                        y: 200,
                                                        disabled: true,
                                                        height: 30,
                                                        id: 'btAddNachDop',
                                                        width: 180,
                                                        icon: 'resources/css/images/ico/add.png',
                                                        text: 'Начислить доп.услугу'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        handler: function(button, e) {
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var grid =  Ext.getCmp('grTarifHousesKv');
                                                            var value = button.findParentByType('form').getValues();
                                                            var getRowSelection = grid.getSelectionModel().getSelection()[0];
                                                            var house_id = getRowSelection.get('house_id');
                                                            //console.log(value);

                                                            var values =stUser.getAt(0);
                                                            var params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"nachislenie_remont_osbb",
                                                                house_id:house_id
                                                            };

                                                            params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"nachislenie_remont_osbb",
                                                                house_id:house_id,
                                                                allkv:value.allkv,
                                                                sdata:value.sdata,
                                                                fdata:value.fdata,
                                                                address_ot:value.address_ot,
                                                                address_do:value.address_do,
                                                                info:value.info
                                                            };
                                                            //console.log(params);

                                                            var myMask= Ext.Msg.show({
                                                                title:'Начисление услуги...',
                                                                msg: 'Начисление услуги .Ожидайте...',
                                                                buttons: Ext.Msg.CANCEL,
                                                                wait: true,
                                                                modal: true,
                                                                icon: Ext.Msg.INFO
                                                            });

                                                            QueryAddress.updateRecords(params,function(results){
                                                                if(results.success==="1"){
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Начисление услуги',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.INFO
                                                                    });
                                                                } else {
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Начисление услуги',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.ERROR
                                                                    });
                                                                }

                                                            });




                                                        },
                                                        x: 630,
                                                        y: 240,
                                                        disabled: true,
                                                        height: 30,
                                                        id: 'btAddNachRemont',
                                                        width: 180,
                                                        icon: 'resources/css/images/ico/add.png',
                                                        text: 'Начислить ремонт'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        handler: function(button, e) {
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var grid =  Ext.getCmp('grTarifHousesKv');
                                                            var value = button.findParentByType('form').getValues();
                                                            var getRowSelection = grid.getSelectionModel().getSelection()[0];
                                                            var house_id = getRowSelection.get('house_id');

                                                            var values =stUser.getAt(0);
                                                            var params = {
                                                                login:values.get('login'),
                                                                password:values.get('password'),
                                                                what:"nachislenie_kvartplata_prev",
                                                                house_id:house_id
                                                            };


                                                            var myMask= Ext.Msg.show({
                                                                title:'Начисление...',
                                                                msg: 'Начисление квартплаты .Ожидайте...',
                                                                buttons: Ext.Msg.CANCEL,
                                                                wait: true,
                                                                modal: true,
                                                                icon: Ext.Msg.INFO
                                                            });

                                                            QueryAddress.updateRecords(params,function(results){
                                                                if(results.success==="1"){
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Начисление квартплаты',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.INFO
                                                                    });
                                                                } else {
                                                                    myMask.close();
                                                                    Ext.MessageBox.show({
                                                                        title: 'Начисление квартплаты',
                                                                        msg: results.msg,
                                                                        buttons: Ext.MessageBox.OK,
                                                                        icon: Ext.MessageBox.ERROR
                                                                    });
                                                                }

                                                            });




                                                        },
                                                        x: 20,
                                                        y: 290,
                                                        disabled: true,
                                                        height: 30,
                                                        id: 'btAddNachKvPrev',
                                                        width: 390,
                                                        icon: 'resources/css/images/ico/add.png',
                                                        text: 'Начислить  квартплату за предыдущий период'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    onComboboxSelect211: function(combo, record, eOpts) {
        //in use

        //STORE
        var stUser = Ext.data.StoreManager.get("StUser");
        var StTarif = Ext.data.StoreManager.get("StTarif");
        var tarif = Ext.getCmp('tarKv');
        var viborTarif = Ext.getCmp('cbTarifKv');
        var form = combo.findParentByType('form');
        var btnInsTarif = Ext.getCmp('btnInsTarifKv');

        //LOGIN & PASSWORD

        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        //LOGIKA
        if (record) {
            if(record.get('house_id') == "188"){
                StTarif.load({
                    params: {
                        what:'TarifFromHouses',
                        login:login,
                        password:password
                        //data:data,
                        //house_id: record.get('house_id')
                    },
                    callback: function(records,operation,success){
                        if(success){
                            viborTarif.clearValue();
                            viborTarif.setDisabled(true);
                            tarif.setValue(0);
                            tarif.setDisabled(true);
                            btnInsTarif.setDisabled(true);
                        }
                    },
                    scope:this
                });
            } else {

                StTarif.load({
                    params: {
                        what:'TarifFromHouse',
                        login:login,
                        password:password,
                        //data:data,
                        house_id: record.get('house_id')
                    },
                    callback: function(records,operation,success){
                        if(success){
                            viborTarif.clearValue();
                            viborTarif.setDisabled(true);
                            tarif.setValue(0);

                        }
                    },
                    scope:this
                });
            }
        }
    },

    onCbTarifKvSelect: function(combo, record, eOpts) {
        //in use

        //STORE

        var form = combo.findParentByType('form');
        var tarif = form.getForm().findField('tar');
        var grid = Ext.getCmp('grTarifHousesKv');
        var btnInsTarif = Ext.getCmp('btnInsTarifKv');
        var selected = record;

        if (record) {
            var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection()[0];

            var size = Ext.Object.getSize(gridRowSelectedRecords) ;
            btnInsTarif.setDisabled(false);
            tarif.setDisabled(false);


            tarif.setValue(gridRowSelectedRecords.get(record.get('tarif')));

        }

    }

});