/*
 * File: app/view/sprav/TabLgotaUtszn.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.view.sprav.TabLgotaUtszn', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tablgotautszn',

    requires: [
        'Osbb.view.sprav.TabLgotaUtsznViewModel',
        'Osbb.view.sprav.TabLgotaUtsznViewController',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.selection.CheckboxModel',
        'Ext.grid.feature.Summary',
        'Ext.grid.feature.GroupingSummary'
    ],

    controller: 'tablgotautszn',
    viewModel: {
        type: 'tablgotautszn'
    },
    id: 'tabLgotaUtszn',
    scrollable: true,
    width: 1460,
    layout: 'fit',
    bodyBorder: false,
    closable: true,
    title: 'Сверка по льготам',
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'fmLgotaUtszn',
            scrollable: true,
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grLgotaUtszn',
                    padding: 10,
                    scrollable: true,
                    bodyBorder: true,
                    title: '',
                    store: 'stLgotaUtszn',
                    viewConfig: {
                        getRowClass: function(record, rowIndex, rowParams, store) {
                            if(record.get('pr') === 0 ){
                                return 'change_color_yellow';

                            } else  {
                                return  'change_color_green';
                            }
                        },
                        height: 700
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'combobox',
                                    width: 220,
                                    fieldLabel: 'ОСМД',
                                    labelWidth: 50,
                                    name: 'osmd_id',
                                    displayField: 'osmd',
                                    queryMode: 'local',
                                    store: 'StOsmd',
                                    valueField: 'osmd_id',
                                    listeners: {
                                        select: 'onComboboxSelect11'
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    formBind: false,
                                    width: 258,
                                    fieldLabel: 'Услуга',
                                    labelWidth: 60,
                                    name: 'usluga_id',
                                    allowBlank: false,
                                    emptyText: 'Выбрать услугу',
                                    displayField: 'usluga',
                                    store: 'StUsluga',
                                    valueField: 'usluga_id',
                                    listeners: {
                                        select: {
                                            fn: 'onComboboxSelect2',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var value = button.findParentByType('form').getValues();
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var tabPnCenter =  Ext.getCmp('tabPnCenter');
                                        var StUtszn = Ext.data.StoreManager.get("stLgotaUtszn");


                                        var grid = button.findParentByType('grid');
                                        var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
                                        var size = Ext.Object.getSize(gridRowSelectedRecords) ;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        var data_nach = form.getForm().findField('data_nach').getValue();
                                        var values =stUser.getAt(0);
                                        var login = values.get('login');
                                        var password = values.get('password');
                                        var params =[];

                                        var report = 'ReestrLgotaUtsznAll';
                                        var namereport = 'Реестр';
                                        var value = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            usluga_id:usluga_id,

                                            osmd_id:osmd_id,
                                            data:data_nach,
                                            report:report,
                                            what:report
                                        };

                                        var tab = tabPnCenter.child('#'+report);
                                        if (!tab) {
                                            tab  = tabPnCenter.add({
                                                xtype:'tabreportorg',
                                                title:namereport,
                                                id:''+report+''
                                            });

                                        }
                                        tabPnCenter.setActiveTab(tab);
                                        var reppan = tab.getComponent(0);
                                        // Basic mask:
                                        var myMask = Ext.Msg.show({
                                            title:'Выписка реестра...',
                                            msg: 'Выписка ...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryKassa.getRaspechatka(value,function(data){
                                            if (data){
                                                reppan.update(data.content);
                                                Ext.REPORTCONTENT =data.content;
                                                Ext.REPORTSQL =data.sql;
                                                Ext.REPORTTITLE =report;
                                                myMask.close();

                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Ошибка ',
                                                    msg: 'Документ не создан',
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });
                                            }
                                        });



                                    },
                                    disabled: true,
                                    id: 'btnPrintLgotaReestrUtszn',
                                    width: 121,
                                    icon: 'resources/css/images/ico/printer.png',
                                    text: 'Реестр'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var value = button.findParentByType('form').getValues();
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var tabPnCenter =  Ext.getCmp('tabPnCenter');
                                        var StUtszn = Ext.data.StoreManager.get("stLgotaUtszn");
                                        var grid = button.findParentByType('grid');
                                        var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
                                        var size = Ext.Object.getSize(gridRowSelectedRecords) ;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();
                                        var data_nach = form.getForm().findField('data_nach').getValue();
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();

                                        var values =stUser.getAt(0);
                                        var login = values.get('login');
                                        var password = values.get('password');
                                        var params =[];

                                        var report = 'AktLgotaUtsznAll';
                                        var namereport = 'Акт сверки';
                                        var value = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            report:report,
                                            usluga_id:usluga_id,
                                            osmd_id:osmd_id,
                                            data:data_nach,
                                            what:report
                                        };
                                        var tab = tabPnCenter.child('#'+report);
                                        if (!tab) {
                                            tab  = tabPnCenter.add({
                                                xtype:'tabreportorg',
                                                title:namereport,
                                                id:''+report+''
                                            });
                                        }
                                        tabPnCenter.setActiveTab(tab);
                                        var reppan = tab.getComponent(0);
                                        // Basic mask:
                                        var myMask = Ext.Msg.show({
                                            title:'Выписка актов сверки...',
                                            msg: 'Выписка актов...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });
                                        QueryKassa.getRaspechatka(value,function(data){
                                            if (data){
                                                reppan.update(data.content);
                                                Ext.REPORTCONTENT =data.content;
                                                Ext.REPORTSQL =data.sql;
                                                Ext.REPORTTITLE =report;
                                                myMask.close();

                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Ошибка ',
                                                    msg: 'Документ не создан',
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });
                                            }
                                        });


                                    },
                                    disabled: true,
                                    id: 'btnPrintLgotaUtszn',
                                    width: 90,
                                    icon: 'resources/css/images/ico/printer.png',
                                    text: 'Акты'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var value = button.findParentByType('form').getValues();
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var tabPnCenter =  Ext.getCmp('tabPnCenter');
                                        var StUtszn = Ext.data.StoreManager.get("stLgotaUtszn");


                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data_nach = form.getForm().findField('data_nach').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        var values =stUser.getAt(0);
                                        var login = values.get('login');
                                        var password = values.get('password');
                                        var report = 'Forma3LgotaUtszn';
                                        var namereport = 'Форма 3';
                                        var value = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data_nach,
                                            osmd_id: osmd_id,
                                            usluga_id:usluga_id,
                                            report:report,
                                            what:report
                                        };

                                        var tab = tabPnCenter.child('#'+report);
                                        if (!tab) {
                                            tab  = tabPnCenter.add({
                                                xtype:'tabreportorg',
                                                title:namereport,
                                                id:''+report+''
                                            });

                                        }
                                        tabPnCenter.setActiveTab(tab);
                                        var reppan = tab.getComponent(0);
                                        // Basic mask:
                                        var myMask = Ext.Msg.show({
                                            title:'Выписка формы...',
                                            msg: 'Выписка ...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });
                                        //console.log(value);
                                        QueryKassa.getRaspechatka(value,function(data){
                                            if (data){
                                                reppan.update(data.content);
                                                Ext.REPORTCONTENT =data.content;
                                                Ext.REPORTSQL =data.sql;
                                                Ext.REPORTTITLE =report;
                                                myMask.close();

                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Ошибка ',
                                                    msg: 'Документ не создан',
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });
                                            }
                                        });
                                    },
                                    disabled: true,
                                    id: 'btnPrintLgotaForma3',
                                    width: 89,
                                    icon: 'resources/css/images/ico/printer.png',
                                    text: 'Форма 3'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO

                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var oplata = form.getForm().findField('oplata').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        var pr = 1;


                                        //STORE

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id:osmd_id,
                                            usluga_id:usluga_id,
                                            oplata:oplata,
                                            pr:pr,
                                            what:'getControlLgotaUtszn'
                                        };



                                        store.load({
                                            params: {
                                                what:'getControlLgotaUtszn',
                                                login:values.get('login'),
                                                osmd_id:osmd_id,
                                                usluga_id:usluga_id,
                                                data:data,
                                                password:values.get('password')
                                            }
                                        });


                                    },
                                    disabled: true,
                                    id: 'btnControlLgotaUtszn',
                                    width: 110,
                                    icon: 'resources/css/images/ico/printer.png',
                                    text: 'Контроль'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'datefield',
                                    width: 201,
                                    fieldLabel: 'Период',
                                    labelWidth: 55,
                                    name: 'data_nach',
                                    format: 'F,Y',
                                    showToday: false,
                                    startDay: 1,
                                    submitFormat: 'Ymd',
                                    listeners: {
                                        select: 'onDatefieldSelect1'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO

                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();

                                        values.set({'usluga_id':usluga_id});
                                        stUser.sync();

                                        //STORE

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            usluga_id:usluga_id,
                                            osmd_id:osmd_id,
                                            what:'update_utszn_lgota'
                                        };
                                        //console.log(params);

                                        //LOGIKA
                                        var myMask= Ext.Msg.show({
                                            title:'Обновление записи...',
                                            msg: 'Обновление записей в базе Ожидайте...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryAddress.updateRecords(params,function(results){
                                            if(results.success==="1"){
                                                store.load({
                                                    params: {
                                                        what:'getLgotaUtszn',
                                                        login:values.get('login'),
                                                        usluga_id:usluga_id,
                                                        data:data,
                                                        osmd_id:osmd_id,
                                                        password:values.get('password')
                                                    }
                                                });

                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы Льгот',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.INFO
                                                });
                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы Льгот',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });

                                            }

                                        });

                                    },
                                    disabled: true,
                                    id: 'btnGetLgotaUtszn',
                                    width: 171,
                                    icon: 'resources/css/images/ico/xsldbg_refresh.png',
                                    text: 'Загрузить льготы'
                                },
                                {
                                    xtype: 'numberfield',
                                    width: 200,
                                    fieldLabel: 'оплата',
                                    labelWidth: 80,
                                    name: 'oplata',
                                    value: 0,
                                    fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO

                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var oplata = form.getForm().findField('oplata').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        var pr = 1;


                                        //STORE

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id:osmd_id,
                                            usluga_id:usluga_id,
                                            oplata:oplata,
                                            pr:pr,
                                            what:'insOplatalgotaUtszn'
                                        };
                                        //console.log(params);

                                        //LOGIKA
                                        var myMask= Ext.Msg.show({
                                            title:'Обновление записи...',
                                            msg: 'Обновление записей в базе Ожидайте...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryAddress.updateRecords(params,function(results){
                                            if(results.success==="1"){
                                                store.load({
                                                    params: {
                                                        what:'getLgotaUtszn',
                                                        login:values.get('login'),
                                                        osmd_id:osmd_id,
                                                        usluga_id:usluga_id,
                                                        data:data,
                                                        password:values.get('password')
                                                    }
                                                });

                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы ',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.INFO
                                                });
                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы ',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });

                                            }

                                        });

                                    },
                                    disabled: true,
                                    id: 'btnInsOplataLgotaUtszn',
                                    width: 149,
                                    icon: 'resources/css/images/ico/yes.png',
                                    text: 'Текущая оплата'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO

                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var oplata = form.getForm().findField('oplata').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        var pr = 2;


                                        //STORE

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id:osmd_id,
                                            oplata:oplata,
                                            usluga_id:usluga_id,
                                            pr:pr,
                                            what:'insOplatalgotaUtszn'
                                        };
                                        //console.log(params);

                                        //LOGIKA
                                        var myMask= Ext.Msg.show({
                                            title:'Обновление записи...',
                                            msg: 'Обновление записей в базе Ожидайте...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryAddress.updateRecords(params,function(results){
                                            if(results.success==="1"){
                                                store.load({
                                                    params: {
                                                        what:'getLgotaUtszn',
                                                        login:values.get('login'),
                                                        osmd_id:osmd_id,
                                                        usluga_id:usluga_id,
                                                        data:data,
                                                        password:values.get('password')
                                                    }
                                                });

                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы ',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.INFO
                                                });
                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы ',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });

                                            }

                                        });

                                    },
                                    disabled: true,
                                    id: 'btnInsDoplataLgotaUtszn',
                                    width: 181,
                                    icon: 'resources/css/images/ico/yes.png',
                                    text: 'Оплата прош периодов'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO

                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var oplata = form.getForm().findField('oplata').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        var pr = 3;


                                        //STORE

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id:osmd_id,
                                            usluga_id:usluga_id,
                                            oplata:oplata,
                                            pr:pr,
                                            what:'insOplatalgotaUtszn'
                                        };
                                        //console.log(params);

                                        //LOGIKA
                                        var myMask= Ext.Msg.show({
                                            title:'Обновление записи...',
                                            msg: 'Обновление записей в базе Ожидайте...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryAddress.updateRecords(params,function(results){
                                            if(results.success==="1"){
                                                store.load({
                                                    params: {
                                                        what:'getLgotaUtszn',
                                                        login:values.get('login'),
                                                        osmd_id:osmd_id,
                                                        usluga_id:usluga_id,
                                                        data:data,
                                                        password:values.get('password')
                                                    }
                                                });

                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы ',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.INFO
                                                });
                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title: 'Обновление базы ',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });

                                            }

                                        });

                                    },
                                    disabled: true,
                                    id: 'btnInsPoplataLgotaUtszn',
                                    width: 109,
                                    icon: 'resources/css/images/ico/yes.png',
                                    text: 'Оплата орг'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;

                                        //STORE
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id : osmd_id,
                                            usluga_id:usluga_id,
                                            what:'input_lgota_oplata'
                                        };


                                        //LOGIKA
                                        var myMask= Ext.Msg.show({
                                            title:'Запись льготы...',
                                            msg: 'Запись в базу оплаты льгот.Ожидайте...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryAddress.updateRecords(params,function(results){
                                            if(results.success==="1"){


                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title:'Запись в базу оплаты льгот...',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.INFO
                                                });
                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title:'Запись в базу оплаты льгот...',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });

                                            }

                                        });
                                    },
                                    disabled: true,
                                    id: 'btnInsLgotaOplata',
                                    width: 211,
                                    icon: 'resources/css/images/ico/add.png',
                                    text: 'Ввод льготы в базу оплаты'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        //COMBO
                                        var grid = button.findParentByType('grid');
                                        var store = grid.store;

                                        //STORE
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = form.getForm().findField('osmd_id').getValue();
                                        var data = form.getForm().findField('data_nach').getValue();
                                        var usluga_id = form.getForm().findField('usluga_id').getValue();

                                        //LOGIKA
                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id : osmd_id,
                                            usluga_id:usluga_id,
                                            what:'otkat_lgota_oplata'
                                        };


                                        //LOGIKA
                                        var myMask= Ext.Msg.show({
                                            title:'Откат льготы...',
                                            msg: 'Откат оплаты льгот.Ожидайте...',
                                            buttons: Ext.Msg.CANCEL,
                                            wait: true,
                                            modal: true,
                                            icon: Ext.Msg.INFO
                                        });

                                        QueryAddress.updateRecords(params,function(results){
                                            if(results.success==="1"){


                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title:'Откат оплаты льгот...',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.INFO
                                                });
                                            } else {
                                                myMask.close();
                                                Ext.MessageBox.show({
                                                    title:'Откат оплаты льгот...',
                                                    msg: results.msg,
                                                    buttons: Ext.MessageBox.OK,
                                                    icon: Ext.MessageBox.ERROR
                                                });

                                            }

                                        });
                                    },
                                    disabled: true,
                                    id: 'btnOtkatLgotaOplata',
                                    width: 77,
                                    icon: 'resources/css/images/ico/add.png',
                                    text: 'Откат'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 30,
                            menuDisabled: true,
                            tooltip: 'Редактировать',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var winprintaktutszn = Ext.ClassManager.instantiateByAlias('widget.winprintaktutszn');
                                        var form = winprintaktutszn.down('#fmPrintAktUtszn');
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var value = record;
                                        //console.log(value);
                                        view.getSelectionModel().select(rowIndex);
                                        form.loadRecord(value);
                                        form.getForm().findField('vibor').setValue('0');
                                        winprintaktutszn.show();
                                    },
                                    icon: 'resources/css/images/ico/edit.png',
                                    tooltip: 'Редактировать'
                                }
                            ]
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 30,
                            menuDisabled: true,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var values =stUser.getAt(0);
                                        var store = view.getStore();
                                        var value = record.data;

                                        var form =  Ext.getCmp('fmLgotaUtszn');
                                        var osmd_id = value.osmd_id;
                                        var data = form.getForm().findField('data_nach').getValue();

                                        var params = {
                                            login:values.get('login'),
                                            password:values.get('password'),
                                            data:data,
                                            osmd_id:osmd_id,
                                            usluga_id:values.get('usluga_id'),
                                            what:'delLgotaUtszn'
                                        };

                                        //GRID


                                        //LOGIKA


                                        Ext.Object.merge(value, params);
                                        //console.log(osmd_id);

                                        Ext.MessageBox.confirm({
                                            title: 'Удаление записи',
                                            msg: 'Вы удаляете запись   <br> Подтвердите или отмените свои действия.',
                                            buttons: Ext.MessageBox.OKCANCEL,
                                            icon: Ext.MessageBox.ERROR,
                                            buttonText:{
                                                ok:'подтвеждаю',
                                                cancel:'отмена'
                                            },
                                            fn:function(btn,newValue){
                                                if(btn=='ok'){
                                                    QueryAddress.updateRecords(value,function(results){
                                                        if(results.success==="1"){
                                                            store.load({
                                                                params: {
                                                                    what:'getLgotaUtszn',
                                                                    login:values.get('login'),
                                                                    osmd_id:osmd_id,
                                                                    usluga_id:values.get('usluga_id'),
                                                                    data:data,
                                                                    password:values.get('password')
                                                                }
                                                            });

                                                            Ext.MessageBox.show({
                                                                title: 'Удаление записи',
                                                                msg: results.msg,
                                                                buttons: Ext.MessageBox.OK,
                                                                icon: Ext.MessageBox.INFO
                                                            });
                                                        } else {
                                                            Ext.MessageBox.show({
                                                                title: 'Удаление записи',
                                                                msg: results.msg,
                                                                buttons: Ext.MessageBox.OK,
                                                                icon: Ext.MessageBox.ERROR
                                                            });

                                                        }

                                                    });
                                                }
                                            }
                                        });
                                    },
                                    icon: 'resources/css/images/ico/no.png',
                                    tooltip: 'Удалить  запись '
                                }
                            ]
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'osmd_id',
                            menuDisabled: true,
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'pr',
                            menuDisabled: true,
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 148,
                            dataIndex: 'address',
                            menuDisabled: true,
                            text: 'Адрес'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 34,
                            dataIndex: 'gr',
                            menuDisabled: true,
                            text: 'Гр',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 100,
                            dataIndex: 'house',
                            menuDisabled: true,
                            text: 'Дом'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 186,
                            dataIndex: 'osmd',
                            menuDisabled: true,
                            text: 'ОСМД'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 40,
                            dataIndex: 'mec',
                            menuDisabled: true,
                            text: 'мес'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            width: 70,
                            dataIndex: 'edrpou',
                            menuDisabled: true,
                            text: 'ЕДРПОУ',
                            format: '0'
                        },
                        {
                            xtype: 'datecolumn',
                            hidden: true,
                            width: 80,
                            align: 'center',
                            dataIndex: 'data',
                            menuDisabled: true,
                            text: 'дата'
                        },
                        {
                            xtype: 'numbercolumn',
                            summaryType: 'sum',
                            width: 85,
                            align: 'right',
                            dataIndex: 'zadol',
                            menuDisabled: true,
                            text: 'Сальдо<br>начало',
                            format: '0.00'
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Начислено в текущем периоде',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'nachisleno',
                                    menuDisabled: true,
                                    text: 'факт',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'norma',
                                    text: 'норма',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'perer',
                                    menuDisabled: true,
                                    text: 'бюджет',
                                    format: '0.00'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'перечислено средств',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0,000.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'oplata',
                                    menuDisabled: true,
                                    text: 'бюджет',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0,000.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'poplata',
                                    menuDisabled: true,
                                    text: 'поставщ',
                                    format: '0.00'
                                }
                            ]
                        },
                        {
                            xtype: 'numbercolumn',
                            summaryRenderer: function(val, params, data) {
                                var n =Ext.util.Format.number(val,'0,000.00');
                                if (val >= 0) {
                                    return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                } else  {
                                    return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                }
                            },
                            summaryType: 'sum',
                            width: 85,
                            align: 'right',
                            dataIndex: 'dolg',
                            menuDisabled: true,
                            text: 'Сальдо<br>конец',
                            format: '0.00'
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Задолженность на начало года',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0,000.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'st',
                                    menuDisabled: true,
                                    text: 'задол',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0,000.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 85,
                                    align: 'right',
                                    dataIndex: 'doplata',
                                    menuDisabled: true,
                                    text: 'оплата',
                                    format: '0.00'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    summaryRenderer: function(val, params, data) {
                                        var n =Ext.util.Format.number(val,'0,000.00');
                                        if (val >= 0) {
                                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                                        } else  {
                                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                                        }
                                    },
                                    summaryType: 'sum',
                                    width: 80,
                                    align: 'right',
                                    dataIndex: 'fin',
                                    menuDisabled: true,
                                    text: 'остаток',
                                    format: '0.00'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 105,
                            dataIndex: 'inn',
                            menuDisabled: true,
                            text: 'инн'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 136,
                            dataIndex: 'fio',
                            menuDisabled: true,
                            text: 'Ф.И.О.'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 133,
                            dataIndex: 'lgota',
                            menuDisabled: true,
                            text: 'Льгота'
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel',
                        mode: 'SIMPLE'
                    },
                    features: [
                        {
                            ftype: 'summary',
                            dock: 'top'
                        },
                        {
                            ftype: 'groupingsummary'
                        }
                    ]
                }
            ]
        }
    ],

    onComboboxSelect11: function(combo, record, eOpts) {
        var stUser = Ext.data.StoreManager.get("StUser");
        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        var StUtszn = Ext.data.StoreManager.get("stLgotaUtszn");
        var btnGetLgotaUtszn =  Ext.getCmp('btnGetLgotaUtszn');
        var btnPrintLgotaUtszn =  Ext.getCmp('btnPrintLgotaUtszn');
        var btnPrintLgotaForma3 =  Ext.getCmp('btnPrintLgotaForma3');
        var btnPrintLgotaReestrUtszn =  Ext.getCmp('btnPrintLgotaReestrUtszn');
        var btnInsLgotaOplata =  Ext.getCmp('btnInsLgotaOplata');
        var btnOtkatLgotaOplata =  Ext.getCmp('btnOtkatLgotaOplata');
        var btnControlLgotaUtszn =  Ext.getCmp('btnControlLgotaUtszn');

        var form =  Ext.getCmp('fmLgotaUtszn');
        var data = form.getForm().findField('data_nach').getValue();
        var usluga_id = form.getForm().findField('usluga_id').getValue();
        // console.log(usluga_id);

        if (usluga_id){
            if (record) {
                values.set({'osmd_id':record.get('osmd_id')});
                stUser.sync();
                btnGetLgotaUtszn.setDisabled(false);
                btnPrintLgotaUtszn.setDisabled(false);
                btnPrintLgotaForma3.setDisabled(false);
                btnPrintLgotaReestrUtszn.setDisabled(false);
                btnInsLgotaOplata.setDisabled(false);
                btnOtkatLgotaOplata.setDisabled(false);
                btnControlLgotaUtszn.setDisabled(false);



                StUtszn.load({
                    params: {
                        what:'getLgotaUtszn',
                        login:login,
                        password:password,
                        data:data,
                        osmd_id:record.get('osmd_id'),
                        usluga_id: usluga_id
                    },
                    scope:this
                });
            }
        }

    },

    onDatefieldSelect1: function(field, value, eOpts) {
        //in use

        //STORE
        var stUser = Ext.data.StoreManager.get("StUser");
        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        var StUtszn = Ext.data.StoreManager.get("stLgotaUtszn");
        var btnGetLgotaUtszn =  Ext.getCmp('btnGetLgotaUtszn');
        var btnPrintLgotaUtszn =  Ext.getCmp('btnPrintLgotaUtszn');
        var btnPrintLgotaForma3 =  Ext.getCmp('btnPrintLgotaForma3');
        var btnPrintLgotaReestrUtszn =  Ext.getCmp('btnPrintLgotaReestrUtszn');
        var btnInsLgotaOplata =  Ext.getCmp('btnInsLgotaOplata');
        var btnOtkatLgotaOplata =  Ext.getCmp('btnOtkatLgotaOplata');
        var btnControlLgotaUtszn =  Ext.getCmp('btnControlLgotaUtszn');


        var form =  Ext.getCmp('fmLgotaUtszn');
        var usluga_id = form.getForm().findField('usluga_id').getValue();
        var osmd_id = form.getForm().findField('osmd_id').getValue();

        //console.log(osmd_id);
        //LOGIN & PASSWORD


        //LOGIKA
        if (usluga_id){
            btnGetLgotaUtszn.setDisabled(false);
            btnPrintLgotaUtszn.setDisabled(false);
            btnPrintLgotaForma3.setDisabled(false);
            btnPrintLgotaReestrUtszn.setDisabled(false);
            btnInsLgotaOplata.setDisabled(false);
            btnOtkatLgotaOplata.setDisabled(false);
            btnControlLgotaUtszn.setDisabled(false);


            StUtszn.load({
                params: {
                    what:'getLgotaUtszn',
                    login:login,
                    password:password,
                    data:value,
                    osmd_id: osmd_id,
                    usluga_id: usluga_id
                },
                scope:this
            });
        }
    }

});