/*
 * File: app/view/sprav/WinAddGasomer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osbb.view.sprav.WinAddGasomer', {
    extend: 'Ext.window.Window',
    alias: 'widget.winaddgasomer',

    requires: [
        'Osbb.view.sprav.WinAddEnergoViewModel1',
        'Osbb.view.sprav.WinAddGasomerViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    controller: 'winaddgasomer',
    viewModel: {
        type: 'spravwinaddgasomer'
    },
    height: 488,
    id: 'winAddGasomer',
    width: 568,
    layout: 'fit',
    title: 'Подключение или редактирование нового газовошо счетчика',
    modal: true,

    items: [
        {
            xtype: 'form',
            height: 560,
            id: 'fmAddGasomer',
            width: 530,
            layout: 'absolute',
            title: '',
            items: [
                {
                    xtype: 'hiddenfield',
                    x: 0,
                    y: 0,
                    fieldLabel: 'Label',
                    name: 'what'
                },
                {
                    xtype: 'hiddenfield',
                    x: 0,
                    y: 0,
                    fieldLabel: 'Label',
                    name: 'gasomer_id'
                },
                {
                    xtype: 'checkboxfield',
                    x: 255,
                    y: 25,
                    id: 'chkExistentGasomer',
                    style: 'background-color: #DCDCDC;',
                    fieldLabel: '',
                    hideEmptyLabel: false,
                    labelWidth: 20,
                    name: 'isjoint',
                    submitValue: false,
                    validateOnChange: false,
                    boxLabel: 'Подключить существующий счетчик',
                    inputValue: '1',
                    uncheckedValue: '0',
                    listeners: {
                        change: 'onChkExistentGasomerChange'
                    }
                },
                {
                    xtype: 'combobox',
                    x: 260,
                    y: 60,
                    hidden: true,
                    id: 'cbExistentGasomer',
                    width: 260,
                    fieldLabel: 'Номер',
                    labelWidth: 60,
                    name: 'joint_id',
                    displayField: 'nomer',
                    store: 'StExistentEnergomer',
                    valueField: 'energomer_id',
                    listeners: {
                        select: 'onCbExistentGasomerSelect'
                    }
                },
                {
                    xtype: 'button',
                    x: 335,
                    y: 400,
                    formBind: true,
                    id: 'btAddGasomer',
                    width: 185,
                    icon: 'resources/css/images/ico/add.png',
                    text: 'Добавить счетчик'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        button.up('#winAddGasomer').close();
                    },
                    x: 35,
                    y: 400,
                    width: 80,
                    icon: 'resources/css/images/ico/delete.png',
                    text: 'Отмена'
                },
                {
                    xtype: 'fieldset',
                    x: 35,
                    y: 95,
                    height: 290,
                    id: 'fcntNewGasomer',
                    style: 'background-color: #DCDCDC;',
                    width: 485,
                    layout: 'absolute',
                    title: '',
                    items: [
                        {
                            xtype: 'numberfield',
                            x: 315,
                            y: 220,
                            width: 145,
                            fieldLabel: 'Первичное показание',
                            labelAlign: 'top',
                            labelWidth: 150,
                            name: 'tek',
                            value: 0,
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения',
                            hideTrigger: true,
                            validateBlank: true,
                            decimalPrecision: 0,
                            minValue: 0
                        },
                        {
                            xtype: 'datefield',
                            x: 315,
                            y: 100,
                            width: 145,
                            fieldLabel: 'дата ввода ',
                            labelAlign: 'top',
                            labelWidth: 150,
                            name: 'sdate',
                            allowBlank: false,
                            format: 'd-m-Y',
                            submitFormat: 'Ymd'
                        },
                        {
                            xtype: 'datefield',
                            x: 5,
                            y: 100,
                            width: 140,
                            fieldLabel: 'дата поверки ',
                            labelAlign: 'top',
                            labelWidth: 150,
                            name: 'pdate',
                            format: 'd-m-Y',
                            submitFormat: 'Ymd'
                        },
                        {
                            xtype: 'datefield',
                            x: 5,
                            y: 160,
                            width: 140,
                            fieldLabel: 'Следующая поверка ',
                            labelAlign: 'top',
                            labelWidth: 150,
                            name: 'fpdate',
                            format: 'd-m-Y',
                            submitFormat: 'Ymd'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 360,
                            y: 35,
                            id: 'jointGasomer',
                            fieldLabel: '',
                            name: 'joint',
                            boxLabel: 'Общий',
                            inputValue: '1',
                            uncheckedValue: '0'
                        },
                        {
                            xtype: 'radiogroup',
                            x: 165,
                            y: 110,
                            height: 160,
                            id: 'rbgPlace2',
                            style: 'background-color: #F1EEEE ;',
                            width: 130,
                            fieldLabel: 'Место установки',
                            labelAlign: 'top',
                            allowBlank: false,
                            columns: 1,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    labelWidth: 80,
                                    name: 'place',
                                    boxLabel: 'Блок',
                                    checked: true,
                                    inputValue: 'блок'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'place',
                                    boxLabel: 'Коридор',
                                    inputValue: 'Коридор'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'place',
                                    boxLabel: 'Кухня',
                                    inputValue: 'Кухня'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'place',
                                    boxLabel: 'ПРУ',
                                    inputValue: 'ПРУ'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'place',
                                    boxLabel: 'Другое',
                                    inputValue: 'Другое'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            x: 60,
                            y: 15,
                            formBind: false,
                            width: 250,
                            fieldLabel: 'Номер',
                            labelWidth: 60,
                            name: 'nomer',
                            allowBlank: false,
                            blankText: 'Поле обязательное для заполнения'
                        },
                        {
                            xtype: 'combobox',
                            x: 60,
                            y: 60,
                            formBind: false,
                            id: 'cbGasomerModel',
                            width: 250,
                            fieldLabel: 'Модель',
                            labelWidth: 60,
                            name: 'model_id',
                            displayField: 'model',
                            queryMode: 'local',
                            store: 'StGmodel',
                            valueField: 'model_id'
                        },
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 220,
                            width: 140,
                            fieldLabel: '№ пломбы',
                            labelAlign: 'top',
                            name: 'plomba'
                        },
                        {
                            xtype: 'textfield',
                            x: 315,
                            y: 155,
                            width: 145,
                            fieldLabel: '№ заводской пломбы',
                            labelAlign: 'top',
                            name: 'zplomba'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    x: 35,
                    y: 25,
                    style: 'background-color: #DCDCDC;',
                    width: 185,
                    fieldLabel: 'текущий адрес_ид',
                    labelWidth: 120,
                    name: 'address_id'
                },
                {
                    xtype: 'textfield',
                    x: 35,
                    y: 60,
                    style: 'background-color: #DCDCDC;',
                    width: 185,
                    fieldLabel: 'новый  адрес_ид',
                    labelWidth: 120,
                    name: 'new_address_id',
                    allowBlank: false,
                    listeners: {
                        change: 'onTextfieldChange'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'dgasomer_id'
                }
            ]
        }
    ]

});